# Generated by Django 5.1.6 on 2025-02-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="categoria",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="precio",
            new_name="price",
        ),
    ]
