# Generated by Django 5.1.6 on 2025-02-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_rename_categoria_products_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="nombre",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
