# Generated by Django 5.1.6 on 2025-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_products_nombre_alter_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
